/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mynilai_22030017;

/**
 *
 * @author ASUS
 */
public class Lutfi_tugas extends javax.swing.JFrame {

    /**
     * Creates new form Lutfi_tugas
     */
    public Lutfi_tugas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JpilihanMataKuliah = new javax.swing.JLabel();
        PilMat = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        aNim = new javax.swing.JLabel();
        bNim = new javax.swing.JTextField();
        aNama = new javax.swing.JLabel();
        bNama = new javax.swing.JTextField();
        aInputJum = new javax.swing.JLabel();
        bInputJum = new javax.swing.JTextField();
        aInputNilaiTugas = new javax.swing.JLabel();
        bInputNilaiTugas = new javax.swing.JTextField();
        aInputNilaiUts = new javax.swing.JLabel();
        bInputNilaiUts = new javax.swing.JTextField();
        aInputNilaiUas = new javax.swing.JLabel();
        bInputNilaiUas = new javax.swing.JTextField();
        dNim = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        aMatkul = new javax.swing.JLabel();
        cNim = new javax.swing.JLabel();
        cNama = new javax.swing.JLabel();
        cNilaiAkhir = new javax.swing.JLabel();
        cGradeNilai = new javax.swing.JLabel();
        dnim = new javax.swing.JTextField();
        dNama = new javax.swing.JTextField();
        dNilaiAkhir = new javax.swing.JTextField();
        dGradeNilai = new javax.swing.JTextField();
        bhitung = new javax.swing.JButton();
        bTutupAplikasi = new javax.swing.JButton();
        bReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("PROSES INPUT NILAI MAHASISWA");

        JpilihanMataKuliah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JpilihanMataKuliah.setText("Pilih Mata Kuliah");
        JpilihanMataKuliah.setFocusTraversalPolicyProvider(true);

        PilMat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PilMat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PBO", "Aljabar Linear", "Analisis Algoritma", "Sistem Basis Data" }));
        PilMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PilMatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(JpilihanMataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(PilMat, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JpilihanMataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PilMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Input Nilai Mahasiswa");

        aNim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        aNim.setText("Input NIM");

        aNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        aNama.setText("Input Nama");

        aInputJum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        aInputJum.setText("Input Jum Presensi Kehadiran");

        bInputJum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInputJumActionPerformed(evt);
            }
        });

        aInputNilaiTugas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        aInputNilaiTugas.setText("Input Nilai Tugas");

        bInputNilaiTugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInputNilaiTugasActionPerformed(evt);
            }
        });

        aInputNilaiUts.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        aInputNilaiUts.setText("Input Nilai UTS");

        aInputNilaiUas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        aInputNilaiUas.setText("Input Nilai UAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(aInputNilaiUas, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bInputNilaiUas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(aInputNilaiUts, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bInputNilaiUts, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(aNama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(aNim)
                                    .addGap(154, 154, 154)))
                            .addGap(29, 29, 29)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(bNim, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bNama, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(aInputJum, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(aInputNilaiTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bInputJum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bInputNilaiTugas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aNim)
                    .addComponent(bNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aNama)
                    .addComponent(bNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aInputJum)
                    .addComponent(bInputJum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aInputNilaiTugas)
                    .addComponent(bInputNilaiTugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aInputNilaiUts)
                    .addComponent(bInputNilaiUts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(bInputNilaiUas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(aInputNilaiUas)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Nilai Akhir Mahasiswa");

        aMatkul.setText("Menampilkan Nama MataKuliah Yang Sudah Dipilih");

        cNim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cNim.setText("NIM                    :");

        cNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cNama.setText("Nama                  :");

        cNilaiAkhir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cNilaiAkhir.setText("Nilai Akhir           :");

        cGradeNilai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cGradeNilai.setText("Grade Nilai          :");

        dnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dnimActionPerformed(evt);
            }
        });

        dNilaiAkhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dNilaiAkhirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dNimLayout = new javax.swing.GroupLayout(dNim);
        dNim.setLayout(dNimLayout);
        dNimLayout.setHorizontalGroup(
            dNimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dNimLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(dNimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dNimLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dNimLayout.createSequentialGroup()
                        .addComponent(aMatkul)
                        .addGap(78, 78, 78))))
            .addGroup(dNimLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(dNimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cNim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cGradeNilai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cNilaiAkhir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cNama, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dNimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dnim, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dNama, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dNilaiAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dGradeNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dNimLayout.setVerticalGroup(
            dNimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dNimLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(dNimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dNimLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dNimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cNim)
                            .addComponent(dnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(dNimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cNama)
                            .addComponent(dNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cNilaiAkhir))
                    .addComponent(dNilaiAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dNimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cGradeNilai)
                    .addComponent(dGradeNilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        bhitung.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bhitung.setText("Hitung");
        bhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhitungActionPerformed(evt);
            }
        });

        bTutupAplikasi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bTutupAplikasi.setText("Tutup Aplikasi");
        bTutupAplikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTutupAplikasiActionPerformed(evt);
            }
        });

        bReset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bhitung)
                                .addGap(37, 37, 37)
                                .addComponent(bReset)
                                .addGap(31, 31, 31)
                                .addComponent(bTutupAplikasi)
                                .addGap(19, 19, 19)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bhitung)
                            .addComponent(bTutupAplikasi)
                            .addComponent(bReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PilMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PilMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PilMatActionPerformed

    private void bhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhitungActionPerformed
        // TODO add your handling code here:
        int aInputJum = Integer.parseInt(bInputJum.getText());
        int aInputNilaiTugas = Integer.parseInt(bInputNilaiTugas.getText());
        int aInputNilaiUts = Integer.parseInt(bInputNilaiUts.getText());
        int aInputNilaiUas = Integer.parseInt(bInputNilaiUas.getText());
        String grade;
        
        double cNilaiAkhir = (0.2 * aInputJum) + (0.2 * aInputNilaiTugas) + (0.3 * aInputNilaiUts) + (0.3 * aInputNilaiUas);
        
        if (cNilaiAkhir >= 80) {
            grade = "A";
    }else if (cNilaiAkhir  >= 65 && cNilaiAkhir <= 79.9){
        grade = "B";   
    }else if (cNilaiAkhir >= 55 && cNilaiAkhir <= 64.9) {
        grade = "C";
    }else if (cNilaiAkhir >= 40 && cNilaiAkhir <= 54.9) {
        grade = "D";
    }else {
        grade = "E";
                
    }
    String nilaiAkhirStr = String.valueOf(cNilaiAkhir);
    aMatkul.setText(PilMat.getSelectedItem().toString());
    dnim.setText(bNim.getText());
    dNama.setText(bNama.getText());
    dNilaiAkhir.setText(nilaiAkhirStr);
    dGradeNilai.setText(grade);
    }//GEN-LAST:event_bhitungActionPerformed

    private void bTutupAplikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTutupAplikasiActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_bTutupAplikasiActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        // TODO add your handling code here:
        bNim.setText("");
        bNama.setText("");
        bInputJum.setText("");
        bInputNilaiTugas.setText("");
        bInputNilaiUts.setText("");
        bInputNilaiUas.setText("");
        dnim.setText("");
        dNama.setText("");
        dNilaiAkhir.setText("");
        dGradeNilai.setText("");
        
    }//GEN-LAST:event_bResetActionPerformed

    private void bInputJumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInputJumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bInputJumActionPerformed

    private void bInputNilaiTugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInputNilaiTugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bInputNilaiTugasActionPerformed

    private void dnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dnimActionPerformed

    private void dNilaiAkhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dNilaiAkhirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dNilaiAkhirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lutfi_tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lutfi_tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lutfi_tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lutfi_tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lutfi_tugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JpilihanMataKuliah;
    private javax.swing.JComboBox<String> PilMat;
    private javax.swing.JLabel aInputJum;
    private javax.swing.JLabel aInputNilaiTugas;
    private javax.swing.JLabel aInputNilaiUas;
    private javax.swing.JLabel aInputNilaiUts;
    private javax.swing.JLabel aMatkul;
    private javax.swing.JLabel aNama;
    private javax.swing.JLabel aNim;
    private javax.swing.JTextField bInputJum;
    private javax.swing.JTextField bInputNilaiTugas;
    private javax.swing.JTextField bInputNilaiUas;
    private javax.swing.JTextField bInputNilaiUts;
    private javax.swing.JTextField bNama;
    private javax.swing.JTextField bNim;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bTutupAplikasi;
    private javax.swing.JButton bhitung;
    private javax.swing.JLabel cGradeNilai;
    private javax.swing.JLabel cNama;
    private javax.swing.JLabel cNilaiAkhir;
    private javax.swing.JLabel cNim;
    private javax.swing.JTextField dGradeNilai;
    private javax.swing.JTextField dNama;
    private javax.swing.JTextField dNilaiAkhir;
    private javax.swing.JPanel dNim;
    private javax.swing.JTextField dnim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
